name: Feature
description: Submit a proposal/request for a new feature
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Confirm this is a new feature request
      description: >
        Select the checkboxes that apply to this feature request. If you're not sure about any of these, don't worry! We'll help you figure it out.
      options:
        - label: Possible new feature in VideoDB Python Client
          required: false
        - label: Potential new feature in VideoDB API
          required: false
        - label: I've checked the current issues, and there's no record of this feature request
          required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: >
        A clear and concise description of what the feature is and why it's needed. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Add any other context about the feature request here.
    validations:
      required: false
